### ISSUE TITLE
The link to the certificates is outdated

### ISSUE THREAD

**Issue by SoulNaturalist** [httptoolkit/httptoolkit-website#51]
![image](https://user-images.githubusercontent.com/58743402/216112065-43d9464a-0d32-484d-9cf5-b2270cfb446c.png)
On [page](https://httptoolkit.com/docs/guides/android/#intercepting-traffic-from-your-own-android-app)

**Comment by pimterry** [comment]
No, I think that's correct! Note the rest of the phrase: `whilst interception is active".

Are you visiting that website via HTTP Toolkit, or are you trying to open it on the normal web? This address doesn't exist on the unmodified internet - it is only accessible when using a client that's connected to HTTP Toolkit, when using HTTP Toolkit's default settings.

You should be able to see this in HTTP Toolkit's default rules on the Mock page (you can click the bin icon in the top right there to reset to the defaults if you've changed them). The default rules there should look like this:

![Screenshot from 2023-02-01 18-09-23](https://user-images.githubusercontent.com/1526883/216112867-58ca6f8a-1c4d-46a8-8a9e-75a3bfd0981f.png)

The expanded rule in this screenshot is what makes this work.

Does that make sense?
