### ISSUE TITLE
404 when trying to download certificate

### ISSUE THREAD

**Issue by radekskrabucha** [httptoolkit/httptoolkit-website#82]
Getting 404 when trying to download certificate from https://amiusing.httptoolkit.tech/certificate

**Comment by pimterry** [comment]
That probably means you're not connected to the proxy, or that you've created a rule that's blocking this. The response to that request is generated by a rule (shown on the Mock page within the Default Rules section). Does that make sense?

**Comment by radekskrabucha** [comment]
All right, that makes sense, now I got it. Thanks 🙏

**Comment by radekskrabucha** [comment]
All right, that makes sense, now I got it. Thanks 🙏
