### ISSUE TITLE
Blog repeatedly scrolls to top in Firefox at some browser widths

### ISSUE THREAD

**Issue by groszdaniel** [httptoolkit/httptoolkit-website#86]
While scrolling down in blog posts (either with the scroll wheel or PgDn), the page repeatedly scrolls to near the top of the body of the post (not the very top of the page), making it impossible to read the rest of the post.

It doesn't happen after every scroll event.

It happens in Firefox, but not in Chromium.

It only happens when the viewport's width is between 1024 and ~1280~ in CSS pixels (wide enough that the title and the picture appear side-by-side, ~but narrow enough that the title's font is less big than with wider browser windows~). Edit: Actually it seems to happen even somewhat above 1280 pixels, but there does appear to be some upper limit.

It happens even in a separate Firefox profile with no extensions and mostly default settings, so it doesn't seem to be caused by an extension.

Example blog post: https://httptoolkit.com/blog/android-14-install-system-ca-certificate/
I use Firefox 130.0.1 on Linux (openSUSE Tumbleweed 20240929), KDE Plasma 6.1.5, X11.
The top of the example blog post:
![Screenshot_20241101_010720](https://github.com/user-attachments/assets/27f8dfbd-1dc4-43a6-b303-1cbe3e2416fc)
Where it gets scrolled up to when scrolling further down:
![Screenshot_20241101_010752](https://github.com/user-attachments/assets/81655010-ba54-48f2-ad8b-57790daab66e)

**Comment by groszdaniel** [comment]
Guides like https://httptoolkit.com/docs/guides/android are also affected, they scroll to the bottom to the table of contents instead. They also seem to be affected by the browser and the viewport width.

**Comment by pimterry** [comment]
This is now fixed! Thanks again for reporting this. It turns out there was an issue between when certain auto-scroll logic for the table of contents kicked in and when the table of contents was made sticky, which resulted in scrolling jumping the whole page around like this. Now properly sorted.

If you run into any other issues, do please let me know.
